In [7]:
# Cell 1 : Import Library

import pandas as pd

In [9]:
# Cell 2 : Read Dataset

data = pd.read_csv("tennis.csv")
data

     outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no

In [11]:
# Cell 3 : Show Dataset Information

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   outlook   14 non-null     object
 1   temp      14 non-null     object
 2   humidity  14 non-null     object
 3   windy     14 non-null     bool
 4   play      14 non-null     object
dtypes: bool(1), object(4)
memory usage: 594.0+ bytes

In [13]:
# Cell 4 : Display First 5 Rows

data.head()

    outlook  temp humidity  windy play
0     sunny   hot     high  False   no
1     sunny   hot     high   True   no
2  overcast   hot     high  False  yes
3     rainy  mild     high  False  yes
4     rainy  cool   normal  False  yes

In [15]:
# Cell 5 : Separate Concepts and Target

concepts = data.iloc[:, :-1].values
target = data.iloc[:, -1].values

print("Concepts:\n", concepts)
print("\nTarget:\n", target)

Concepts:
 [['sunny' 'hot' 'high' False]
 ['sunny' 'hot' 'high' True]
 ['overcast' 'hot' 'high' False]
 ['rainy' 'mild' 'high' False]
 ['rainy' 'cool' 'normal' False]
 ['rainy' 'cool' 'normal' True]
 ['overcast' 'cool' 'normal' True]
 ['sunny' 'mild' 'high' False]
 ['sunny' 'cool' 'normal' False]
 ['rainy' 'mild' 'normal' False]
 ['sunny' 'mild' 'normal' True]
 ['overcast' 'mild' 'high' True]
 ['overcast' 'hot' 'normal' False]
 ['rainy' 'mild' 'high' True]]

Target:
 ['no' 'no' 'yes' 'yes' 'yes' 'no' 'yes' 'no' 'yes' 'yes' 'yes' 'yes' 'yes'
 'no']

In [17]:
# Cell 6 : Initialize Hypothesis with First Positive Example

for i in range(len(target)):
    if target[i] == "yes":
        hypothesis = concepts[i].copy()
        break

print("Initial Hypothesis:")
print(hypothesis)

Initial Hypothesis:
['overcast' 'hot' 'high' False]

In [19]:
# Cell 7 : Apply Find-S Algorithm

for i in range(len(concepts)):
    
    if target[i] == "yes":
        
        for j in range(len(hypothesis)):
            
            if hypothesis[j] != concepts[i][j]:
                hypothesis[j] = '?'
        
        print("After Example", i + 1, ":", hypothesis)

After Example 3 : ['overcast' 'hot' 'high' False]
After Example 4 : ['?' '?' 'high' False]
After Example 5 : ['?' '?' '?' False]
After Example 7 : ['?' '?' '?' '?']
After Example 9 : ['?' '?' '?' '?']
After Example 10 : ['?' '?' '?' '?']
After Example 11 : ['?' '?' '?' '?']
After Example 12 : ['?' '?' '?' '?']
After Example 13 : ['?' '?' '?' '?']

In [21]:
# Cell 8 : Final Hypothesis

print("\nFinal Hypothesis:")
print(hypothesis)

Final Hypothesis:
['?' '?' '?' '?']